version: '3'
services:
  tagebuch_client:
    build: client/.
    restart: always
    ports:
      - "127.0.0.1:4340:3000"
  database:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: example

