version: '3'
services:
  client:
    build: 
      context: client/.
      args:
        PUBLIC_BASE_URL: ws://localhost:4123
    restart: always
    ports:
      - "127.0.0.1:4340:3000"
  server:
    build: server/.
    restart: always
    ports:
      - "127.0.0.1:4123:4123"
    environment:
      HOST: 0.0.0.0
      PORT: 4123
      DB_HOST: database
      DB_USER: postgres
      DB_PASS: example
      DB_PORT: 5432
  database:
    image: postgres
    restart: always
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - tagebuch_data:/var/lib/postgresql/data

volumes:
  tagebuch_data:
